/**
 * `results/*.json` -> `results/summary.md`.
 *
 * The tables the finding quotes, regenerated from the raw output rather than
 * transcribed, so a re-run cannot silently disagree with the prose.
 */
import * as fs from 'node:fs';
import * as path from 'node:path';
import {fileURLToPath} from 'node:url';

const HERE = path.dirname(fileURLToPath(import.meta.url));
const RESULTS = path.join(HERE, '../results');

const ENGINES = ['chromium', 'firefox', 'webkit'];
const read = (f: string) => (fs.existsSync(f) ? JSON.parse(fs.readFileSync(f, 'utf-8')) : undefined);

const out: string[] = ['# Summary', '', '_Generated by `run/summarise.ts`. Do not edit._', ''];

const fsRun = read(path.join(RESULTS, 'fs.json'));
if (fsRun) {
	out.push('## Filesystem', '');
	out.push(`Node ${fsRun.env.node} on ${fsRun.env.cpus}, writing to \`${fsRun.env.dirRoot}\``);
	out.push(`(tmpfs: **${fsRun.env.dirIsTmpfs}** — on tmpfs a rename and a rewrite are both memory ops)`, '');
	out.push('| layout | size | seal | case | staging segs | renames | rewrites | bytes written | ms |');
	out.push('| --- | --- | --- | --- | --- | --- | --- | --- | --- |');
	for (const row of fsRun.rows) {
		const p = row.promotion;
		out.push(
			`| ${row.layout} | ${row.size} | ${row.sealAfter} | ${row.sharingCase} | ${row.segments.staging} | ` +
				`${p.metadataRenames} | ${p.payloadsRewritten} | ${(row.syscalls.bytesWritten / 1e6).toFixed(1)} MB | ` +
				`${p.ms.toFixed(0)} |`,
		);
	}
	out.push('');
}

const engineRuns = ENGINES.map((e) => [e, read(path.join(RESULTS, `browser-${e}.json`))] as const).filter(
	([, run]) => run,
);
if (engineRuns.length > 0) {
	out.push('## IndexedDB', '');
	out.push('Promotion wall-clock in ms, per engine.', '');
	out.push(`| arm | size | seal | case | staging segs | rewrites | ${ENGINES.join(' | ')} |`);
	out.push(`| --- | --- | --- | --- | --- | --- | ${ENGINES.map(() => '---').join(' | ')} |`);
	const keyed = new Map<string, any>();
	for (const [engine, run] of engineRuns) {
		for (const row of run.rows) {
			const k = `${row.arm}|${row.size}|${row.sealAfter}|${row.sharingCase}`;
			const entry = keyed.get(k) ?? {row, ms: {}};
			entry.ms[engine] = row.results.promotion?.ms;
			keyed.set(k, entry);
		}
	}
	for (const [, {row, ms}] of keyed) {
		const p = row.results.promotion ?? {};
		out.push(
			`| ${row.arm} | ${row.size} | ${row.sealAfter} | ${row.sharingCase} | ${row.results.segments?.staging} | ` +
				`${p.payloadsRewritten} | ` +
				ENGINES.map((e) => (ms[e] === undefined ? '-' : ms[e].toFixed(0))).join(' | ') +
				' |',
		);
	}
	out.push('');
}

fs.writeFileSync(path.join(RESULTS, 'summary.md'), out.join('\n'));
console.log(`results/summary.md (${out.length} lines)`);
